server:
  port: 8000

spring:
  main:
    allow-circular-references: true
  application:
    name:
  datasource:
    url: jdbc:postgresql://localhost:5432/librarydb
    username: postgres
    password: senha
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
<<<<<<< HEAD
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
=======
>>>>>>> a75693c09ee9223d8a8755cccb1bf0fb32bc9c0a
